<?php
/**
 * @file
 * Code for the GSB Feature Announcement Content Type feature.
 */

include_once 'gsb_feature_announcement_ct.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for announcement node edit form.
 */
function gsb_feature_announcement_ct_form_announcement_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id != 'announcement_node_form') {
    return;
  }

  $language = $form['language']['#value'];

  $form['field_link_key_audio']['#states'] = array(
    'visible' => array(
      ':input[name="field_icon[' . $language . ']"]' => array(
        array('value' => 'audio'),
      ),
    ),
  );

  $form['field_link_key_video']['#states'] = array(
    'visible' => array(
      ':input[name="field_icon[' . $language . ']"]' => array(
        array('value' => 'video'),
      ),
    ),
  );

  // Hide alumni fields if the alumni checkbox is not checked.
  $form['field_program_single']['#states']['invisible'][':input[name="field_alumni_story[' . $language . ']"]'] = array(
    array('checked' => FALSE),
  );
}

/**
 *  Implements hook_field_group_pre_render_alter().
 */
function gsb_feature_announcement_ct_field_group_pre_render_alter(&$element, $group, &$form) {
  // Hide field group for alumni name if alumni checkbox is not checked.
  if ($element['#id'] == 'node_announcement_form_group_alumni_name') {
    $language = $form['language']['#value'];
    $element['#states']['invisible'][':input[name="field_alumni_story[' . $language . ']"]'] = array(
      array('checked' => FALSE),
    );
  }
}
